---
title: "Running an analysis plan"
author: "Martin Barner"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Running an analysis plan}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = F
)
library(knitr)

```


### Load package
```{r,warning=FALSE,message=FALSE,error=FALSE}
library(hypegrammaR)
library(dplyr)
```
### Prepare Inputs



### Load input
For details please see <a href="input_formats.html">Input formats & loading files</a>

```{r,warning=F,message=F,error=F}
stop(getwd())
assessment_data<-read.csv("../tests/testthat/testdata.csv",stringsAsFactors = F)
```

```{r,warning=F,message=F,error=F}
samplingframe<-read.csv("../tests/testthat/test_samplingframe.csv",stringsAsFactors = F)
```

```{r,warning=F,message=F,error=F}
weights<-map_to_weighting(sampling.frame = samplingframe,
                          data.stratum.column = "stratification",
                          sampling.frame.population.column = "population",
                          sampling.frame.stratum.column = "strata.names",
                          data = assessment_data)
```

```{r,warning=F,message=F,error=F}
questions<-read.csv("../tests/testthat/test_questionnaire_questions.csv")
choices<-read.csv("../tests/testthat/test_questionnaire_choices.csv")

questionnaire<-load_questionnaire(data = assessment_data,
                                  questions = questions,
                                  choices = choices,
                                  choices.label.column.to.use = "label::English"
)
```

```{r,warning=F,message=F,error=F}

analysisplan<-load_analysisplan(file = "../tests/testthat/test_analysisplan.csv")

```

### Run the analysis plan & save outputs as an html file

```{r,eval = F}

list_of_results <- assessment_data %>%   from_analysisplan_map_to_output(analysisplan = analysisplan,
                                                                        weighting = weights,
                                                                        questionnaire = questionnaire) 

  
```

### Output as html
```{r,eval = F}

list_of_results %>% map_to_template(questionnaire = questionnaire,
                                    dir = "../",
                                    filename = "my_example_report.html")

```



